---
editor_options: 
  markdown: 
    wrap: sentence
---


```{r include=FALSE}

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.topcaption=TRUE)

library(tidyverse)
library(janitor)
library(lubridate)
library(haven)
library(glue)
library(gt)
library(comunicacion)
library(hrbrthemes) 
library(ggtext) 
library(data.table)
library(herramientas)

### Se defininen algunos parámetros

#anio de referencia de publicación
options(scipen = 9999)

anio_ref <- 2023

```


# **Turismo Internacional en Argentina** {#turismo-internacional}

## Introducción

En el presente capítulo se analizan los distintos aspectos relacionados al turismo receptivo y emisivo de la Argentina. Para ello, se toman como base las siguientes fuentes que abarcan los distintos aspectos de la actividad turística:

* Estimaciones de la cantidad de **viajes de turistas y excursionistas**[^viaje] elaboradas por la DNMyE en base a datos de la Dirección Nacional de Migraciones (DNM) de la totalidad de los pasos fronterizos del país y de la Encuesta de Turismo Internacional (ETI). Es decir, del flujo de viajes de turistas y excursionistas no residentes que visitaron el país y residentes que viajaron al exterior, por todos los medios de transporte (aéreo, fluvial/marítimo y terrestre). 

[^viaje]: El viaje realizado por un visitante no residente (turismo receptivo) se registra desde
el momento que llega a la Argentina hasta que sale. Un visitante no residente
(turista o excursionista) puede salir de Argentina para efectuar visitas a otros países
y volver a ingresar en un corto período de tiempo, antes de regresar a su país de
residencia habitual. Por ello, la cantidad de viajes receptivos puede ser mayor que la
cantidad de turistas/excursionistas receptivos. En tanto, el viaje realizado por un visitante residente en Argentina (turismo emisivo) se registra desde el momento en que sale del país hasta que retorna, independientemente de la cantidad de países visitados. Por ello, la cantidad de
viajes emisivos coincide con la cantidad de visitantes emisivos. El primer apartado presenta los datos de **viajes de turistas/excursionistas**, pero no de turistas/excursionistas. En el segundo apartado la unidad de análisis sí serán los **turistas**. 

* Datos de la Dirección Nacional de Estadísticas del Sector Externo y Cuentas Internacionales (DNESEyCI) del INDEC, que dicha dirección elabora para la construcción de la cuenta viajes del balance de pagos, con información sobre el **gasto turístico**[^nota_empalme] emisivo y receptivo por todos los medios de transporte de ingreso y egreso del país, es decir los pasos terrestres, fluviales, marítimos y aéreos.

* La Encuesta de Turismo Internacional (ETI) que estudia la evolución y las características de los **turistas residentes y no residentes** (turismo emisivo y receptivo) por el Aeropuerto internacional de Ezeiza, el Aeroparque Jorge Newbery,
el Aeropuerto Internacional Pajas Blancas de Córdoba, Aeropuerto Internacional de Mendoza, el Puerto de Buenos Aires y el Paso Internacional Cristo Redentor. 


[^nota_empalme]:Tanto en 2013 como en 2016 dicho organismo realizó mejoras en las estimaciones de los datos, gracias a un conjunto de revisiones metodológicas y a una mayor explotación de los datos migratorios. Para poder tener una serie comparable, desde la DNMyE se realizó un empalme de la serie a partir de las variaciones trimestrales por medio de transporte y país de la serie anterior. 

En la primera sección, inicialmente, se presentarán  los indicadores más importantes acerca de la evolución general de los **viajes de turistas** residentes y no residentes en base a los datos de la DNMyE. Luego, se mostrará información sobre el **gasto y estadía** con datos de  la DNESEyCI del INDEC.

En el segundo apartado, se realizará un análisis más exhaustivo del **perfil de los turistas** internacionales que ingresan y egresan por los aeropuertos internacionales de Ezeiza, Córdoba, Mendoza, Aeroparque Jorge Newbery, el Puerto de Buenos Aires y el paso Cristo Redentor, en base a datos de la ETI.

En todo el capítulo, se presentan los datos desagregados por país de residencia para el receptivo y por país de destino para el emisivo, agrupados de la siguiente forma: cada uno de los países limítrofes (Bolivia, Brasil, Chile, Paraguay, Uruguay), EE.UU.y Canadá, Resto de América, Europa y Resto del mundo.

A la hora de analizar la información de ambas secciones, es relevante considerar que el turismo internacional en 2021 aún estuvo afectado por la pandemia de la COVID-19; por lo que **la información presentada referida tanto al volumen de turistas (y sus gastos), como el perfil de los mismos puede llegar a presentar diferencias con respecto al resto de los años**. 

